---
# meta/qb.yml file for qb/ruby/gem/release
# 
# qb settings for this role. see README.md for more info.
#

description: |
  Release a gem, handling version change, tagging, committing, pushing, etc.
  
  Depends on `rake` and `bundler` gems, using the `release` task that
  {Bundler::GemHelpers} provides.

# prefix for role variables
var_prefix: gem_release

# how to get a default for `dir` if it's not provided as the
default_dir: null

# Set to false to not save options
save_options: false

options:
# - name: example
#   description: an example of a variable.
#   required: false
#   type: boolean # boolean (default) | string
#   short: e
