# NOTE  May be possible to test multiple languages:
#       
#       https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
#       
#       Though seems like that runs them in different instances, where as we
#       just need Python and NodeJS available in the Ruby spec... which I
#       figured out, see below...
# 

# disable the default submodule logic
# See https://gist.github.com/iedemam/9830045
git:
  submodules: false

os:
  - linux
  - osx

before_install:
  # Use sed to replace the SSH URL with the public URL, then init and update
  # submodules
  # - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - ./test/bin/git-submod-ssh-to-https.rb
  - git submodule update --init --recursive
  
  # Travis has 2.7.14 pre-installed in pyenv, so use that
  # - pyenv install 2.7.13
  - pyenv list
  - pyenv global 2.7.14
  
  # Install requirements (Ansible and QB Python module/filter deps)
  - pip install -r requirements.txt
  
  - which ansible-playbook
  - ansible --version
  
  # Install `//package.json` to get `semver`
  - yarn
  
  # Install gem
  - gem update --system
  - gem install bundler
  
language: ruby

rvm:
  # The min Ruby requirement in the gemspec
  - 2.3.0
  # The most recent patch of all more recent minor versions
  - 2.3.6
  - 2.4.3
  - 2.5.0

script: bundle exec rspec

sudo: false

cache: bundler
