# NOTE  Everything is collected together into a single shell script:
#       
#       https://github.com/travis-ci/travis-ci/issues/7472#issuecomment-286910242
#       
#       so it's important to `source` other scripts so they affect the
#       environment in the right way.
#       

# Disable the default submodule logic, since we need to transform the paths
# from SSH -> HTTPS first.
# 
# See notes in `//test/ci/travis/before_install.inc.bash`
# 
git:
  submodules: false

os:
  - linux
  - osx

before_install:
  - source ./test/ci/travis/before_install.inc.bash
  
language: ruby

rvm:
  # The min Ruby requirement in the gemspec
  - 2.3.0
  # The most recent patch of all more recent minor versions
  - 2.3.6
  - 2.4.3
  - 2.5.0

script: bundle exec rspec

sudo: false

cache: bundler
