# NOTE  May be possible to test multiple languages:
#       
#       https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
#       
#       Though seems like that runs them in different instances.
# 

# disable the default submodule logic
# See https://gist.github.com/iedemam/9830045
git:
  submodules: false

python: 2.7.13

before_install:
  # Use sed to replace the SSH URL with the public URL, then init and update
  # submodules
  - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  
  # Travis has 2.7.14 pre-installed in pyenv, so use that
  # - pyenv install 2.7.13
  - pyenv global 2.7.14
  
  # Install requirements (Ansible and QB Python module/filter deps)
  - pip install -r requirements.txt
  
  # Install `//package.json` to get `semver`
  - yarn
  
  # Install gem
  - gem update --system
  - gem install bundler
  
language: ruby

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

script: bundle exec rspec --fail-fast

sudo: false

cache: bundler
