---
# tasks file for qb.git_check_clean

- name: >
    get git status for repo {{ git_check_clean_dir }}
  shell: git status --porcelain 2>/dev/null
  args:
    chdir: "{{ git_check_clean_dir }}"
  register: git_check_clean_status
  changed_when: false

- name: >
    fail if the repo has any untracked or modified files
  fail:
    msg: >
      repo at {{ git_check_clean_dir }} can not have any untracked or
      modified files, please commit or stash and retry.
  when: (git_check_clean_status.stdout_lines | length) != 0

