---
##############################################################################
# Main tasks for `qb/docker/image` role
##############################################################################

# - qb.docker.image.get_args: >-
#     {{ vars | select_by_keys( 'startswith', 'docker_image' ) }}
#   register: response
# 
# - debug: var=response

# See http://docs.ansible.com/ansible/latest/modules/docker_image_module.html
# - name: >-
#     Invoke `docker_image` to manage the image
#   docker_image:
    
