#!/usr/bin/env qb setup
---
- name: Setup development environment for nrser/qb project

  hosts: localhost

  # Any tasks the need to run *before* the roles.
  pre_tasks:
    
  # /pre_tasks

  roles:
  
  - role: qb/dev/ref/repo/git
    full_name: ansible/ansible
    version: v2.4.1.0-1
  
  - role: qb/dev/ref/repo/git
    full_name: nrser/nrser.env
    # version: HEAD (implicit)
    
  - role: qb/dev/ref/repo/git
    full_name: beiarea/workstations
    
  - role: qb/dev/ref/repo/git
    full_name: nrser/ansible-nrser.profile
  
  - role: qb/dev/ref/repo/git
    full_name: erikhuda/thor
    version: v0.20.0
  
  # /roles
  
  tasks:
  
    - name: Install gems
      bundler:
        gem_path: ./.bundle
  
  # /tasks

# / play
