---
# playbook to setup the dev env for this repo
- name: dev setup for nrser/qb

  hosts: localhost

  pre_tasks:
  - name: load dev_setup facts
    dev_setup_facts:

  roles:
  - role: nrser.dev_setup
    # repos that are co-developed
    dev_setup_repos:
    - owner: nrser
      name: gitignore
      
    - owner: nrser
      name: ansible-nrser.dev_setup

    # sources that are used for reference only
    dev_setup_refs:
      github:
      - owner: ansible
        name: ansible
        version: v1.9.4-1
        dir_name: ansible-v1.9.4
        depth: 1
      
      - owner: nrser
        name: nrser.env
      
      - owner: beiarea
        name: workstations
      
      - owner: nrser
        name: ansible-nrser.profile
      
      archive: []

  tasks:
