---
# meta/qb.yml file for qb.role
# 
# qb settings for this role. see README.md for more info.
#

# prefix for role variables
var_prefix: null

# how to get a default for `dir` if it's not provided as the 
default_dir: null

vars:  
- name: role_name
  type: string
  description: name of the role.
  short: n

- name: files
  type: boolean
  description: create a files directory.
  short: f

- name: handlers
  type: boolean
  description: create handlers/main.yml
  short: a

- name: meta
  type: boolean
  description: create meta/main.yml
  short: m

- name: tasks
  type: boolean
  description: create tasks/main.yml
  short: t

- name: templates
  type: boolean
  description: create a templates directory.
  short: e

- name: vars
  type: boolean
  description: create vars/main.yml
  short: v

- name: project
  type: boolean
  description: create a project repo for this role

- name: project_owner
  type: string
  description: the github owner of the project repo
  
- name: project_name
  type: string
  description: the github name of the project repo

- name: project_hub
  type: boolean
  description: switch to `hub create` the project repo
  