---
##############################################################################
# QB metadata for `qb/python/pip` role.
# 
# QB settings for this role.
# 
# @see http://www.rubydoc.info/gems/qb/file/doc/qb_roles/metadata.md
#
##############################################################################

# Shown in help output, etc.
description: >-
  TODO describe qb/python/pip role

# Gemspec-style requirements. Right now only `.gems.qb` is used.
requirements:
  gems:
    # Role options taking advantage of the {NRSER::Types} system require
    # QB 0.4.
    # 
    # TODO  Change this to `>= 0.4.0` when 0.4.0 is released.
    # 
    qb: '>= 0.4.0.dev'

# Prefix for role variables
var_prefix: pip

# How to get a default for `DIRECTORY` arg if not provided by user.
# 
# @see http://www.rubydoc.info/gems/qb/file/doc/qb_roles/metadata/default_dir.md
# 
default_dir: null

# If `true`, QB will ensure `DIRECTORY` exists before starting the play.
mkdir: false

# Default user to become for play
default_user: null

# Save options in `.qb-options.yml` files
save_options: true

# Options to pass to `ansible-playbook`
ansible_options: {}

# Role CLI options that become Ansible vars
options:
  # - name: example
  #   description: an example of a variable.
  #   required: false
  #   type: boolean # boolean (default) | string
  #   short: e
  
  - include: qb/python/config
    as: false