---
# tasks file for qb.qb_role

- name: create meta directory
  file:
    path: "{{ role_dest }}/meta"
    state: directory

- name: create meta/qb.yml
  template:
    src: qb.yml.j2
    dest: "{{ role_dest }}/meta/qb.yml"
    force: false

- include: module.yml
  with_items: "{{ qb_role_modules }}"
  loop_control:
    loop_var: qb_role_module
  