---
- set_fact:
    qb_role_module_class: "{{ qb_role_module | class_case }}"
    qb_role_module_path: "{{ qb_role_dest }}/library/{{ qb_role_module }}"
  
- name: "create {{ qb_role_module }} module"
  template:
    src: module.rb.j2
    dest: "{{ qb_role_module_path }}"
    force: "{{ role_force }}"

- name: "make library/{{ qb_role_module }} executable"
  file:
    path: "{{ qb_role_module_path }}"
    mode: a+x
