---
# create a new npm package to hack
- name: add everything 
  command: git add --all .
  args:
    chdir: "{{ qb_dir }}"

- name: commit everything 
  command: git commit -m "init"
  args:
    chdir: "{{ qb_dir }}"
  
- name: push
  command: git push --set-upstream origin master
  args:
    chdir: "{{ qb_dir }}"

- name: remove it
  file:
    path: "{{ qb_dir }}"
    state: absent