---
# tasks file for qb.gitignore

- name: create directory
  file:
    path: "{{ gitignore_dest }}"
    state: directory

- name: create .gitignore
  copy:
    content: ''
    dest: "{{ gitignore_dest }}/.gitignore"
    force: "{{ gitignore_force }}"

- name: modify .gitignore
  blockinfile:
    content: "{{ gitignore_content }}"
    dest: "{{ gitignore_dest }}/.gitignore"
    beginmarker: |
      {{ '#' * 78 }}
      # BEGIN {{ gitignore_tag }}
      #
    endmarker: |
      #
      # END {{ gitignore_tag }}
      {{ '#' * 78 }}
