---
# tasks file for qb.gitignore

- set_fact:
    gitignore_repo: ./tmp/gitignore-{{ gitignore_version }}

- name: check out nrser/gitignore
  git:
    repo: git@github.com:nrser/gitignore.git
    dest: "{{ gitignore_repo}}"
    version: v{{ gitignore_version }}
    depth: 1
    update: false

- name: create .gitignore
  copy:
    content: ''
    dest: "{{ dir }}/.gitignore"
    force: false

- name: modify .gitignore
  blockinfile:
    content: "{{ lookup('file', gitignore_repo + '/' + gitignore_name + '.gitignore') }}"
    dest: "{{ dir }}/.gitignore"
    beginmarker: |
      {{ '#' * 78 }}
      # BEGIN {{ gitignore_name }}.gitignore
      #
    endmarker: |
      #
      # END {{ gitignore_name }}.gitignore
      {{ '#' * 78 }}
