---
# tasks file for qb.gitignore

- name: check out nrser/gitignore
  git:
    repo: git@github.com:nrser/gitignore.git
    dest: ./tmp/gitignore
    version: master
    depth: 1
    update: "{{ gitignore_update }}"

- name: create .gitignore
  copy:
    content: ''
    dest: "{{ dir }}/.gitignore"
    force: false

- name: modify .gitignore
  blockinfile:
    content: "{{ lookup('file', './tmp/gitignore/' + gitignore_name + '.gitignore') }}"
    dest: "{{ dir }}/.gitignore"
    beginmarker: |
      {{ '#' * 78 }}
      # BEGIN {{ gitignore_name }}.gitignore
      #
    endmarker: |
      #
      # END {{ gitignore_name }}.gitignore
      {{ '#' * 78 }}
