---
# tasks file for qb.gitignore

- name: create .gitignore
  copy:
    content: ''
    dest: "{{ qb_dir }}/.gitignore"
    force: "{{ gitignore_force }}"

- name: modify .gitignore
  blockinfile:
    content: "{{ lookup('file', 'gitignore/' + gitignore_name + '.gitignore') }}"
    dest: "{{ qb_dir }}/.gitignore"
    beginmarker: |
      {{ '#' * 78 }}
      # BEGIN {{ gitignore_name }}.gitignore
      #
    endmarker: |
      #
      # END {{ gitignore_name }}.gitignore
      {{ '#' * 78 }}
