#!/usr/bin/env ruby

require 'json'

HERE = File.dirname(__FILE__)
GITIGNORE_DIR = File.expand_path File.join HERE, '..', 'files', 'gitignore'

names = Dir.chdir(GITIGNORE_DIR) do
  Dir['**/*.gitignore'].map {|path|
    path.match(/(.*)\.gitignore/)[1]
  }
end

puts JSON.pretty_generate({
  save_options: false,
  
  default_dir: {
    find_up: '.gitignore',
  },
  
  # TODO  added this to preserve prefix from when role was named 
  #       `qb.gitignore`, might want to change once we sort all that out.
  #     
  var_prefix: 'gitignore',
  
  vars: [
    {
      name: "name",
      description: "name of gitignore.",
      required: true,
      type: {
        one_of: names,
      },
      short: 'n',
    },
  ],
})