---
##############################################################################
# Ansible metadata for `qb/ruby/rspec/setup` role
##############################################################################

allow_duplicates: no

dependencies: []
# - role: role-name
