---
##############################################################################
# QB metadata for `qb/ruby/rspec/setup` role.
# 
# QB settings for this role.
# 
# @see http://www.rubydoc.info/gems/qb/file/doc/qb_roles/metadata.md
#
##############################################################################

# Shown in help output, etc.
description: >-
  TODO describe qb/ruby/rspec/setup role

# Gemspec-style requirements. Right now only `.gems.qb` is used.
requirements:
  gems:
    qb: '>= 0.3.0'

# Prefix for role variables
var_prefix: setup

# How to get a default for `DIRECTORY` arg if not provided by user.
# 
# @see http://www.rubydoc.info/gems/qb/file/doc/qb_roles/metadata/default_dir.md
# 
default_dir: null # means use *must* provide `DIRECTORY` arg

# If `true`, QB will ensure `DIRECTORY` exists before starting the play.
mkdir: false

# Default user to become for play
default_user: null

# Save options in `.qb-options.yml` files
save_options: true

# Options to pass to `ansible-playbook`
ansible_options: {}

# Role CLI options that become Ansible vars
options: []
# - name: example
#   description: an example of a variable.
#   required: false
#   type: boolean # boolean (default) | string
#   short: e
