---
# meta file for nrser.js

allow_duplicates: yes

dependencies:
- role: nrser.state_mate
  
- role: qb.npm_package
  npm_package_main: lib/index.js
  npm_package_scripts: "{{ nrser_js_package_scripts }}"
  