---
# meta file for qb.install_gem
allow_duplicates: yes

dependencies:
- role: qb/ruby/gem/build

- role: nrser.rbenv_gem
  rbenv_gem_rubies: >-
    {{ gem_install_rubies }}
  rbenv_gem_name: >-
    {{ gem_root_facts.gem.name }}
  # Ugh... this is named "source" because that's what it's called in Ansible's
  # `gem` module, but it's *not* the source directory, it's the `.gem` file
  rbenv_gem_source: >-
    {{ gem_build_path }}
  rbenv_gem_state: present
