---
# tasks file for qb/git/check/clean

- name: >
    Get git status for repo {{ git_root }}
  shell: git status --porcelain 2>/dev/null
  args:
    chdir: "{{ git_root }}"
  register: git_check_clean_status
  changed_when: false

- name: >
    Fail if the repo at {{ git_root }} has any untracked or modified files.
  fail:
    msg: >
      Repo at {{ git_root }} can not have any untracked or
      modified files, please commit or stash and retry.
  when: (git_check_clean_status.stdout_lines | length) != 0

