---

- set_fact:
    project_dev_dir: "{{ project_dest }}/dev"

# dev
# ====

- name: >-
    Create `//dev`
  git_mkdir:
    path: "{{ project_dev_dir }}"

# dev/bin
# ========

- name: >-
    Create `//dev/bin` directory
  git_mkdir:
    path: "{{ project_dev_dir }}/bin"
  when: project_dev_bin

# scratch
# =======

- name: >-
    Create `//dev/scratch` directory
  git_mkdir:
    path: "{{ project_dev_dir }}/scratch"
  when: project_scratch


# setup
# ============================================================================

- when: project_setup
  name: >-
    Add `//dev/setup.qb.yml` to setup the project development environment via
    `qb setup` (or executing `setup.qb.yml`)
  block:
  - name: Create `//dev/setup.qb.yml`
    template:
      src: setup.qb.yml.j2
      dest: >-
        {{ project_dev_dir }}/setup.qb.yml
      force: >-
        {{ project_force }}
  
  - name: Make `//dev/setup.qb.yml` executable
    file:
      dest: >-
        {{ project_dev_dir }}/setup.qb.yml
      mode: 0755
