# setup
# =====

- name: create dev/bootstrap.yml
  template:
    src: bootstrap.yml.j2
    dest: "{{ project_dev_dir }}/bootstrap.yml"
    force: "{{ project_force }}"

- name: create dev/setup.yml
  template:
    src: setup.yml.j2
    dest: "{{ project_dev_dir }}/setup.yml"
    force: "{{ project_force }}"

- name: create dev/ansible.cfg
  copy:
    src: ansible.cfg
    dest: "{{ project_dev_dir }}/ansible.cfg"
    force: "{{ project_force }}"

- name: create dev/hosts
  copy:
    src: hosts
    dest: "{{ project_dev_dir }}/hosts"
    force: "{{ project_force }}"

- name: create /dev/.gitignore
  copy:
    content: ''
    dest: "{{ project_dev_gitignore }}"
    force: "{{ project_force }}"

- name: ingore setup related stuff
  lineinfile:
    line: "{{ item }}"
    dest: "{{ project_dev_gitignore }}"
  with_items:
  - /repos
  - /ref/tmp
  - /lib/dev_setup
  - "*.pyc"
