---
# tasks file for qb.project

# bin
# ===

- name: create /bin directory
  git_mkdir:
    path: "{{ qb_dir }}/bin"
  when: project_bin

# dev
# ===

- include: dev.yml
  when: project_dev

# tmp
# ===

- name: create tmp directory
  git_mkdir:
    path: "{{ qb_dir }}/tmp"
    # have to explicitly commit it since it's ignored 
    commit: true
  when: project_tmp
    
- name: ignore tmp dir in git
  lineinfile:
    line: /tmp
    dest: "{{ qb_dir }}/.gitignore"
  when: project_tmp

# readme
# ======

- name: create readme
  template:
    src: README.md.j2
    dest: "{{ qb_dir }}/README.md"
    force: "{{ project_force }}"
  when: project_readme

# hub
# ===

- name: run `hub create`
  command: "hub create{% if project_private %} -p{% endif %} {{ project_owner }}/{{ project_name }}"
  args:
    chdir: "{{ qb_dir }}"
  when: project_hub

# qb artifacts
# ============

- name: ignore .qb-playbook.yml
  lineinfile:
    line: .qb-playbook.yml
    dest: "{{ qb_dir }}/.gitignore"
  when: project_tmp