---
# tasks file for qb.project

# bin
# ===

- name: create /bin directory
  git_mkdir:
    path: "{{ dir }}/bin"
  when: project_bin

# dev
# ===

- name: create /dev
  git_mkdir:
    path: "{{ dir }}/dev"
  when: project_dev or project_setup

- name: create /dev/bin directory
  git_mkdir:
    path: "{{ dir }}/dev/bin"
  when: project_dev and project_dev_bin

# setup
# =====

- include: setup.yml
  when: project_setup

# scratch
# =======

- name: create scratch directory
  git_mkdir:
    path: "{{ dir }}/scratch"

# tmp
# ===

- name: create tmp directory
  git_mkdir:
    path: "{{ dir }}/tmp"
    
- name: ignore tmp dir in git
  lineinfile:
    line: /tmp
    dest: "{{ dir }}/.gitignore"
  register: ignore_tmp

# readme
# ======

- name: create readme
  template:
    src: README.md.j2
    dest: "{{ dir }}/README.md"
    force: false
  when: project_readme

# hub
# ===

- name: run `hub create`
  command: "hub create{% if project_private %} -p{% endif %}"
  args:
    chdir: "{{ dir }}"
  when: project_hub
