---
# playbook to setup the dev env for this repo
- name: dev setup for nrser/qb

  hosts: localhost

  pre_tasks:
  - name: load dev_setup facts
    tags:
    - always
    dev_setup_facts:

  roles:
  - role: nrser.dev_setup
    tags:
    - dev-setup
    # repos that are co-developed
    dev_setup_repos: []

    # sources that are used for reference only
    dev_setup_refs:
      github:
      - owner: ansible
        name: ansible
        version: v2.3.2.0-1
        dir_name: ansible@v2.3.2.0
      
      - owner: nrser
        name: nrser.env
      
      - owner: beiarea
        name: workstations
      
      - owner: nrser
        name: ansible-nrser.profile
      
      archive: []

  tasks:
  - name: install gems
    bundler:
      chdir: "{{ dev_setup_project_root }}"
      gem_path: ./.bundle
