---
- name: >-
    homebrew_name is 'yarn' if no versions is specified,
    else it is 'yarn@<version>'.
  set_fact:
    yarn_setup_brew_name: >-
      {{ 'yarn@'+yarn_setup_version if yarn_setup_version else 'yarn' }}


- name: >-
    `yarn_setup_can_brew_create` is true when the `yarn_setup_brew_create` 
    option is `true` and the state is either 'linked' or 'present'.
  set_fact:
    yarn_setup_can_brew_create: >-
      {{ yarn_setup_brew_create and yarn_setup_state == 'present' }}

- debug:
    msg: >-
      update_homebrew {{ lookup( 'every', 'update_homebrew', days=1 ) }}

- name: >-
    Make sure `{{ yarn_setup_brew_name }}` is {{ yarn_setup_state }}
    on macOS via Homebrew.
  homebrew:
    name: >-
      {{ yarn_setup_brew_name }}
    state: >-
      {{ yarn_setup_state }}
    update_homebrew: >-
      {{ lookup( 'every', 'update_homebrew', days=1 ) }}
  # ignore errors if we're in a config where we can create the formula
  ignore_errors: >-
    {{ yarn_setup_can_brew_create }}
  register: yarn_setup_brew_result

# - debug: var=yarn_setup_brew_result
# 
# - fail: msg=HERE


- when: >-
    'failed' in yarn_setup_brew_result and
    yarn_setup_can_brew_create
  name: >-
    Create Homebrew formula
  include: "{{ role_path }}/tasks/distribution/MacOSX/brew_create.yml"


- name: >-
    Link Yarn in Homebrew
  when: yarn_setup_brew_link
  homebrew:
    name: "{{ yarn_setup_brew_name }}"
    state: linked
    install_options:
    - overwrite
    