---
# meta/qb.yml file for stdio
# 
# qb settings for this role. see README.md for more info.
#

# description of the role to show in it's help output.
description: null

# prefix for role variables
var_prefix: null

# how to get a default for `dir` if it's not provided as the only
# positional argument. if a positional argument is provided it will
# override the method defined here.
# 
# options:
# 
# -   null
#     -   require the value on the command line.
# -   git_root
#     -   use the git root fof the directory that the `qb` command is invoked
#         from. useful for 'project-centric' commands so they can be invoked
#         from anywhere in the repo.
# -   cwd
#     -   use the directory the `qb` command is invoked form.
# -   {exe: PATH}
#     -   invoke an execuable, passing a JSON serialization of the options
#         mapping their CLI names to values. path can be relative to role
#         directory.
default_dir: cwd

# default user to become for play
default_user: null

# set to false to not save options in .qb-options.yml files
save_options: false

options:
# - name: example
#   description: an example of a variable.
#   required: false
#   type: boolean # boolean (default) | string
#   short: e

- name: log
  description:
  type: array
  required: false
  short: l

- name: raise
  description: raise an error in main.
  required: false
  type: boolean
  short: r

- name: count
  description: count to 10 on stdout with 1 sec sleeps between
  required: false
  type: boolean
  short: c
