---
# tasks file for qb/ref/repo/git

- name: >-
    Clone {{ full_name }}@{{ version }} Git repo for reference.
  git:
    repo: >-
      {{ ssh_user }}@{{ host }}:{{ full_name }}.git
    dest: >-
      {{ dest }}
    version: >-
      {{ version }}
    depth: >-
      {{ depth }}
    update: >-
      {{ update }}

- name: >-
    Add a line in //dev/ref/.gitignore to ignore the `{{ rel_dest }}` clone.
  lineinfile:
    dest: >-
      {{ project_root }}/dev/ref/.gitignore
    line: >-
      /{{ rel_dest }}
    create: true
