---
# tasks file for ansible_module

- when: rebundle
  block:
  - name: Run a {QB::Ansible::Module} using the "rebundle" loader
    scratch.ansible_module.rebundled:
      x: ex

  - debug: var=rebundled_says


- when: autorun
  block:
  - name: Run a {QB::Ansible::Module} using the "autorun" loader
    scratch.ansible_module.autorun:
      x: ex
    register: autorun_result

  - debug: var=autorun_result


- when: script
  block:
  - name: Run a {QB::Ansible::Module} using the "script" loader
    scratch.ansible_module.script:
      x: why oh why?
    register: script_result
  
  - debug: var=script_result
  - debug: var=ur
