---
# tasks file for qb.yarn_setup

- name: Manage Yarn installation on MacOSX
  include: "{{ role_path }}/tasks/distribution/{{ ansible_distribution }}/main.yml"

- name: Add global Yarn packages
  with_items: "{{ yarn_setup_global_packages }}"
  stream:
    cmd: "yarn global add {{ item }}"
  