#!/usr/bin/env ruby

require 'pathname'
require 'pp'
require 'yaml'
require 'json'
require 'fileutils'
require 'thread'

require 'cmds'

require 'qb'

require 'nrser/refinements'
using NRSER


DEBUG_ARGS = ['-D', '--DEBUG']


def set_debug! args
  if DEBUG_ARGS.any? {|arg| args.include? arg}
    QB::Util::Logging.setup level: :debug
    DEBUG_ARGS.each {|arg| args.delete arg}
  end
end


def main args
  Thread.current.name = 'main'
  logger = SemanticLogger['qb/exe/qb#main']
  
  set_debug! args
  logger.debug args: args
  
  QB.check_ansible_version
  
  logger.debug "Switch arg" => args[0]
  
  status = case args[0]
  when nil, '-h', '--help', 'help'
    QB::CLI.help
  when 'play'
    QB::CLI.play args.rest
  when 'run'
    QB::CLI.run args.rest
  when 'setup'
    state_args = args.rest
    
    case state_args[0]
    when nil
      QB::CLI.setup
    end
  else
    # default to `run` on the full args
    QB::CLI.run args
  end
  
  logger.debug "Exit status", status
  
  # exit status
  exit status
end


main(ARGV) # if __FILE__ == $0 # doesn't work with gem stub or something?
