---
# defaults file for qb/ref/repo/git
project_root: >-
  {{ qb_dir }}

version: HEAD

host: github.com

ssh_user: git

protocol: ssh

depth: 1

update: false

owner: >-
  {{ full_name.split('/')[0] }}

repo_name: >-
  {{ full_path.split('/')[1] }}

full_name: >-
  {{ owner }}/{{ repo_name }}

rel_dest: >-
  {{ name }}@{{ version }}

dest: >-
  {{ project_root }}/dev/ref/{{ rel_dest }}
  