---
##############################################################################
# Ansible metadata for `qb/docker/image` role
##############################################################################

allow_duplicates: yes

dependencies: []
# - role: role-name

