---
# tasks file for qb.gem

# preamble... should move to facts?

- name: get ruby version
  command: ruby -e "puts RUBY_VERSION"
  register: gem_ruby_version
  changed_when: false

- name: get bundler version
  command: bundle --version
  register: gem_bundler_version
  changed_when: false

# ok, actual work....

- name: add /bin/console
  template:
    src: console.j2
    dest: "{{ dir }}/bin/console"
    force: false
    mode: a+x

- name: add /bin/setup
  copy:
    src: setup
    dest: "{{ dir }}/bin/setup"
    force: false
    mode: a+x

- name: create /lib
  file:
    path: "{{ dir }}/lib"
    state: directory

- name: add /lib/<dirname>.rb
  template:
    src: module.rb.j2
    dest: "{{ dir }}/lib/{{ gem_dirname }}.rb"
    force: false

- name: create /lib/<dirname>
  file:
    path: "{{ dir }}/lib/{{ gem_dirname }}"
    state: directory

- name: add /lib/<dirname>/version.rb
  template:
    src: version.rb.j2
    dest: "{{ dir }}/lib/{{ gem_dirname }}/version.rb"
    force: false

- name: add /.rspec
  copy:
    src: .rspec
    dest: "{{ dir }}/.rspec"
    force: false

- name: add /.travis.yml
  template:
    src: .travis.yml.j2
    dest: "{{ dir }}/.travis.yml"
    force: false

- name: add {{ gem_name }}.gemspec
  template:
    src: gemspec.j2
    dest: "{{ dir }}/{{ gem_name }}.gemspec"
    force: false

- name: add /Gemfile
  template:
    src: Gemfile.j2
    dest: "{{ dir }}/Gemfile"
    force: false

- name: add /LICENSE.txt
  template:
    src: "{{ gem_license }}-LICENSE.txt.j2"
    dest: "{{ dir }}/LICENSE.txt"
    force: false
  when: gem_license is defined

- name: add /Rakefile
  copy:
    src: Rakefile
    dest: "{{ dir }}/Rakefile"
