##
# Create
##

- name: >-
    Make sure the `yard` opts file at `{{ yard_opts_file_path }}` contains
    the "-" line that separates options from args, creating if needed
  lineinfile:
    path: >-
      {{ yard_opts_file_path }}
    line: '-'
    insertafter: EOF
    create: true


- name: >-
    Stat README.md
  stat:
    path: >-
      {{ bundle_root | path_join( 'README.md' ) }}
  register: yard_setup_readme_stat


- when: >-
    yard_setup_readme_stat.stat.exists
  name: >-
    Add README.md to `{{ yard_opts_file_path }}`
  lineinfile:
    dest: >-
      {{ yard_opts_file_path }}
    line: README.md
    insertafter: '^\-\s?$'


- name: >-
    Add `doc/**/*.md` extra files to `{{ yard_opts_file_path }}`
  lineinfile:
    dest: >-
      {{ yard_opts_file_path }}
    line: 'doc/**/*.md'
    insertafter: '^\-\s?$'


- name: >-
    Set `plugin`, `markup-provider`, `output-dir` and `markup` settings in
    {{ yard_opts_file_path }}
  with_dict:
    output-dir: >-
      {{ yard_output_rel_dir }}
    plugin: yard-commonmarker
    markup-provider: commonmarker
    markup: markdown
  lineinfile:
    path: >-
      {{ yard_opts_file_path }}
    line: >-
      --{{ item.key }} {{ item.value }}
    regexp: '^--{{ item.key | regex_escape() }}[\ \=]'
    insertbefore: '^\-\s?$'
