---
##############################################################################
# Main tasks for `qb/python/config` role
##############################################################################

- with_items:
    - py_use_v2
    - pip_exe
  debug:
    msg: "{{ lookup( 'vars', item ) }}"
