---
##############################################################################
# Ansible metadata for `qb/ruby/yard/config` role
##############################################################################

allow_duplicates: yes

dependencies: []
# - role: role-name

